spring:
  application:
    name: eureka-server
server:
  port: 8080
eureka:
  server:
    enable-self-preservation: false
    registry-sync-retry-wait-ms: 500
    a-sgcache-expiry-timeout-ms: 60000
    eviction-interval-timer-in-ms: 30000
    peer-eureka-nodes-update-interval-ms: 15000
    renewal-threshold-update-interval-ms: 15000
  client:
    fetch-registry: true
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
